### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by yleflour** [brianfoody/react-native-brainblocks#1]
Hello,

I would like to contribute to this project but there are no contribution guidelines.

I would love be added as a contributor in order to create PRs and help you with this project.

Here is what I can do:
- Setup a publishing flow
- Setup linting community standards
- Setup test coverage
- Setup flow coverage
- Setup storybook
- Refactor your components in multiple files for better readability
- Involve some UX/UI designers to figure out a way to make this really sexy

**Comment by brianfoody** [comment]
You the man. I will add you as a contributor now. 

I was thinking of ways to improve the UI as well. I have been using lottie in my own projects to enhance the flow of interactions.

I think something like this would really add to it.

https://www.lottiefiles.com/1331-done
